### ISSUE TITLE
Using Script with Unity Animator

### ISSUE THREAD

**Issue by lbryan212** [WiggleWizard/quake3-movement-unity3d#12]
Hello, I just wanted to say thanks for porting over the code as I have my character controller bhoping all over the place. My only question would be how could I get this working in animator so i can have my model working with blend tree animations. I tried creating parameters such as moveSpeed, speed, velocity, etc. Do I need to rewrite this script to be functional inside Animator?

Anything would be much appreciated.

**Comment by WiggleWizard** [comment]
Unfortunately this script only covers the actual movement of the character and I cannot help with animations or anything further than bugs in the script itself.
