### ISSUE TITLE
Weird air control issue while strafe jumping

### ISSUE THREAD

**Issue by Pixelch3f** [WiggleWizard/quake3-movement-unity3d#9]
This is quite hard to explain but here goes.

When using air control and strafe jumping, if you let go of the strafe key while facing another direction (say, 45 degrees off the way you're travelling), the player very quickly goes towards that direction while in the air.  

I have tried everything I can think of to try and stop this but no luck.

Any ideas?

**Comment by Zinglish** [comment]
Are you trying to simulate VQ3 or CPMA?

**Comment by Zinglish** [comment]
Actually, I think I know what you're talking about and I may have seen this before. It's probably got something to do with the order of processing, I'll take a look at it if I have time today and attempt a fix!

**Comment by Pixelch3f** [comment]
CPMA and using CS :)

**Comment by Pixelch3f** [comment]
Alright, I believe I've done the pull request now. Let me know!

**Comment by TechnikEmpire** [comment]
Air control is broken because he flat out stole this code from http://games.linuxdude.com/tamaps/archive/cpm1_dev_docs/ which is closed-source (was leaked, not legal) and has no idea what he's really doing, except stealing other people's work of course.
